version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: pnpm run start:debug
    env_file:
      - .env.local
    networks:
      - webnet
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_LOCAL_USERNAME: ${DB_USER}
      MONGO_LOCAL_PASSWORD: ${DB_PASSWORD}
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongodata:
  node_modules:
